# @package _group_
#
# Default project 

# MLflow configs
experiment:
  name: Default

# Data configs
data:
  dataset: 
    name: cifar10
    rootdir: /workspace/datasets
    classes: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
    num_class: 10
    num_shot: 20
  sampler:
    name: balanced_batch_sampler

# Training configs
train:
  batch_size: 10
  epochs: 3
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    name: cross_entropy
  metric:
    name: classification
  save_best_ckpt: True
  num_workers: 2

# Model configs
model:
  name: resnet18
  pretrained: False
  initial_ckpt: 