# Default project 

# Import presets
defaults:
  - hydra/job_logging: custom
  - data/dataset: cifar10
  - data/sampler: balanced_batch_sampler
  - train/trainer: default
  - train/criterion: cross_entropy
  - train/metric: classification
  - model: simple_cnn

# MLflow configs
experiment:
  name: Default

# Training configs
train:
  batch_size: 10
  epochs: 1
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  eval: False
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001

# Model configs
model:
  initial_ckpt: 