### Default configs ###
# Data configs
data:
  dataset_name: cifar10
  dataset_root: ./datasets

# Training configs
train:
  batch_size: 10
  epochs: 100
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    name: cross_entropy
  metric:
    name: classification
  save_best_ckpt: True
  num_workers: 2
  sampler_name: balanced_batch_sampler
  class_num: 10
  classes: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
  shot_num: 20
  logdir: ./logs/

# Model configs
model:
  name: resnet18
  pretrained: False
  initial_ckpt: 
    # e.g) initial_ckpt: ./logs/2020-07-26T00:19:34.918002/ckpt/best_acc_ckpt.pth if resume. Blank if not resume
