### Default configs ###
# Data configs
data:
  dataset_name: omniglot 
  dataset_root: ./datasets
  dataroot: 
    train: ./data/dataset/train
    val: ./data/dataset/val
    test: ./data/dataset/test
  labelroot: 
    train: ./data/dataset/label/train
    val: ./data/dataset/label/val
    test: ./data/dataset/label/test

# Training configs
train:
  batch_size: 8
  epochs: 50
  optimizer:
    type: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    type: cross_entropy
  n_gpus: 1
  save_ckpt_interval: 10
  num_workers: 2
  sampler_name: balanced_batch_sampler
  class_num: 8
  shot_num: 15

# Model configs
model:
  name: fcn_resnet50
  n_classes: 21
  pretrained: False
  resume: 
    # e.g) resume: ./logs/2020-07-26T00:19:34.918002/ckpt/best_acc_ckpt.pth if resume. Blank if not resume

# Other configs
util:
  logdir: ./logs/
